name: C# CI Formatting

on:
  pull_request:
    branches:
      - main # 対象のブランチ
    types: [opened, synchronize, reopened]

jobs:
  build-format:
    name: Build, Format Check
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./ # ソリューションファイル(sln, slnx?)の場所

    steps:
      # ソースコードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # .NET SDKのセットアップ
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.101'

      # フォーマットの検証
      # --verify-no-changes オプションでフォーマット違反がある場合はエラー
      - name: Check Formatting
        run: dotnet format --verify-no-changes --verbosity diagnostic PlusPim.slnx
